version: '3.8'

services:
  myapp:
    image: nginx:alpine
    environment:
      - VERSION=stable
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - myapp_stable
      - myapp_canary
    networks:
      - appnet

networks:
  appnet:
    driver: overlay 